version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: data-mgt-system-sb-postgres-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: data_mgt_system_dev
    ports:
      - '5432:5432'
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - dev_network

  redis:
    image: redis:7
    container_name: data-mgt-system-sb-redis-dev
    ports:
      - '6379:6379'
    volumes:
      - redis_data_dev:/data
    networks:
      - dev_network

volumes:
  postgres_data_dev:
  redis_data_dev:

networks:
  dev_network:
